//SCRIVI UN PROGRAMMA CHE STAMPI I NUMERI DA 1 A 100 
//PER I MULTIPLI DI 3 STAMPO "FIZZ"
//PER I PER I MULTIPLI DI 5 STAMPO "BUZZ"
//PER I MULTIPLI CHE SONO SIA DI 3 CHE DI 5 STAMPO "FIZZBUZZ"

//CREO IL CONTATORE CON IL CICLO FOR

for(let i = 1; i <= 100; i++){
    console.log(i)
}